"""Path and filesystem constants for Neuro-CXG."""

from pathlib import Path

# --- PROJECT STRUCTURE ---
PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_ROOT = PROJECT_ROOT / "data"
DATA_PROCESSED = DATA_ROOT / "processed"
DATA_TIME_SERIES = DATA_PROCESSED / "time_series"
DATA_FINAL = DATA_ROOT / "final"
DATA_IMAGES = DATA_ROOT / "images"
DATA_ATLASES = DATA_ROOT / "raw" / "atlases"
DATA_METADATA = DATA_ROOT / "metadata"

# Final split directories
FINAL_TRAIN = DATA_FINAL / "train"
FINAL_VAL = DATA_FINAL / "val"
FINAL_TEST = DATA_FINAL / "test"

MODEL_ROOT = PROJECT_ROOT / "models"
CHECKPOINT_DIR = MODEL_ROOT / "checkpoints"

# Baseline (pre-trained) checkpoints shipped with the repository.
# New training runs save to CHECKPOINT_DIR; get_active_checkpoint_dir() resolves
# the correct directory at runtime.
BASELINE_CHECKPOINT_DIR = MODEL_ROOT / "checkpoints_baseline"
RESULTS_DIR = PROJECT_ROOT / "results"

# Result subdirectory constants — import these instead of hardcoding paths
RESULTS_TRAINING_DIR = RESULTS_DIR / "experiments" / "training"
RESULTS_ABLATIONS_DIR = RESULTS_DIR / "experiments" / "ablations"
RESULTS_DATA_QUALITY_DIR = RESULTS_DIR / "experiments" / "data_quality"
RESULTS_EVALUATION_DIR = RESULTS_DIR / "evaluation"
CONFIG_DIR = PROJECT_ROOT / "configs"

# --- FILE PATHS ---
CONFIG_BRAIN_YAML = CONFIG_DIR / "brain.yaml"
ATLAS_PATH = DATA_ATLASES / "AAL3v1.nii"
ATLAS_METADATA = DATA_METADATA / "atlas_metadata.json"
PHENO_PATH = DATA_PROCESSED / "Phenotypic_V1_0b_preprocessed1.csv"
MASTER_MANIFEST = DATA_METADATA / "master_manifest.csv"

# Output files for the pipeline
NODE_ATTRIBUTES_TEMPORAL = DATA_METADATA / "node_attributes_temporal.csv"
NODE_ATTRIBUTES_HARMONIZED = DATA_METADATA / "node_attributes_harmonized.csv"
HARMONIZED_FOLDS_DIR = DATA_METADATA / "harmonized_folds_cv"
NODE_FEATURES_3D = DATA_METADATA / "node_features_3d.csv"
# Harmonized spatial CSV (all 6 YOLO columns preserved for ComBat; model only reads 4).
# graph_factory reads only x/y/z_depth/size — conf_std and detection_count are excluded
# from model input because they encode scanner quality (site) not brain structure.
# Generated by fold_safe_harmonization.main(); graph_factory prefers this when present.
NODE_FEATURES_3D_HARMONIZED = DATA_METADATA / "node_features_3d_harmonized.csv"
CAUSAL_GRAPHS_DIR = DATA_PROCESSED / "causal_graphs"
# Task 2: multi-view causal graphs stored per-subject under this directory
CAUSAL_GRAPHS_MULTIVIEW_DIR = DATA_PROCESSED / "causal_graphs_multiview"
